### ISSUE TITLE
License requirements for ONTAP to ONTAP tiering 

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloud-manager-tiering#17]
Page: [Set up licensing for Cloud Tiering](https://docs.netapp.com/us-en/cloud-manager-tiering/task-licensing-cloud-tiering.html)

This document references that ONTAP to SG does not need any licensing. As far as I'm aware ONTAP to ONTAP tiering doesn't require a license but I don't see this documented anywhere. 

Figure that could be quickly added in to clarify for readers.

**Comment by TheFalldog** [comment]
Pretty sure it's been supported for awhile now. Info on the solution is documented here at least, https://docs.netapp.com/us-en/ontap/s3-config/enable-ontap-s3-access-remote-fabricpool-task.html and https://docs.netapp.com/us-en/ontap/s3-config/enable-ontap-s3-access-local-fabricpool-task.html

Thanks

**Comment by netapp-tonacki** [comment]
Hi,  My note was about whether we have claimed support in Cloud Tiering thru Cloud Manager.  I realize ONTAP has had this support for a while.  I have sent a note to the team to see what they have to say.  I'll let you know what I hear.

Thanks, Tom

**Comment by TheFalldog** [comment]
Ah, I've fallen for our crappy terminology shift. You're probably right, I haven't heard anything from the CM team on this. Feel free to close.

**Comment by netapp-tonacki** [comment]
I think the plan is to support it thru Cloud Tiering at some point...  so I'll close this for now.  I'll let you know what I hear.

Thanks, Tom
