### ISSUE TITLE
Gov Cloud Support

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloud-manager-tiering#23]
Page: [Supported Azure Blob access tiers and regions](https://docs.netapp.com/us-en/cloud-manager-tiering/reference-azure-support.html)

Would it be possible to update this page (and the AWS & GCP pages) to reflect support for gov cloud regions? The hyperscalers tend to use different nomenclature than what's listed for their gov specific regions. 

Thanks!

**Comment by netapp-tonacki** [comment]
Hi FallDog,  Thanks for your feedback.  To my knowledge, Cloud Tiering is not supported in government regions. Have you heard that it is?

Thanks, Tom

**Comment by TheFalldog** [comment]
Yeah, I take back what I said. Depends on how much you take some of these docs at face value. I'll ping you if any more info come to light, for now go ahead and nuke this request.
