### ISSUE TITLE
CTS Endpoint?

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloud-manager-tiering#24]
Page: [Tiering data from on-premises ONTAP clusters to Azure Blob storage](https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-azure.html)

In this doc it says "An outbound internet connection to the Cloud Tiering service over port 443 (HTTPS)"

I don't see where this specific service's endpoint is described. In other words, what exactly is the destination for port 433 that needs to be put into a firewall config?

Thanks,!

**Comment by netapp-tonacki** [comment]
Hi, Falldog.  Thanks for your comment.  I see in the docs for Azure ports (https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-azure.html#advanced-outbound-rules) where 443 is mentioned.  Is that helpful?

Thanks, Tom

**Comment by TheFalldog** [comment]
Hey Tom,

The implication is that there's a specific target for port 443. If a customer is poking holes in their firewall, what exactly should they target? Is it bluexp.netapp.com? Cloudmanager.netapp.com? Or some other endpoint?

Hope that helps.

Thanks!

**Comment by netapp-tonacki** [comment]
Hi, Falldog,  Sorry for the delay.  I tracked down that the endpoints that must be accessible are defined in the Connector topic https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-set-up-networking-azure.html#endpoints-contacted-for-day-to-day-operations .  They should already be set up correctly from when they set up their Connector.  I will add a link to that topic to clarify.

Thanks, Tom
