### ISSUE TITLE
suggested wording review to clarify better

### ISSUE THREAD

**Issue by bdeloure** [NetAppDocs/cloud-manager-tiering#26]
Page: [Tiering data from on-premises ONTAP clusters to S3 object storage](https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-s3-compat.html)

Under Quick Start for "Tier to S3 object storage" there is a list of you need the following for minimum requirements.  I understand that this doc is telling you what you need as a source in on-prem ONTAP 9.8.  And I confirmed this by going to the other Tier to docs that point to other object storage and read those minimum requirements as the source.

However, beginning in ONTAP 9.8, ONTAP began offering ONTAP S3 as supported protocol to run an on-prem object storage solution.  This document could be interpreted as you can tier to ONTAP S3 using Cloud Tiering and use the S3-compatible service provider.  It's not clear if that's true, but if it is, there is a warning above on that page that "NetApp does not support nor is liable for any issues . . ." which would not be the case if it does work as NetApp does support ONTAP S3.

I think until ONTAP S3 is supported as an official Cloud Tiering provider type with the proper signatures, the same way that FabricPool works for on-prem with ONTAP S3, it might be good to explain this particular context in the Cloud Tiering doc a little more clearly.

It's not clear from that page if the requirements apply to the Tiering source and destination.

**Comment by netapp-tonacki** [comment]
Hi bdeloure,  I see your point that some users might know about ONTAP's S3 support and could be confused.  I can update that section to make sure it's clear that we're talking about the source system.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi, I was making some other small updates to the Tiering docs, so I added more information to clarify that we're talking about the "source" ONTAP system.  Let me know what you think.  https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-s3-compat.html

Thanks, Tom

**Comment by bdeloure** [comment]
Tom,

That's much better and most accurate to how things work today.  I've gone ahead and requested that the Cloud Tiering PM consider adding ONTAP S3 as an official tiering provider for on-prem in the roadmap.  This way we can say it's all supported and works if a customer wants to do it from Cloud Tiering the same as they can StorageGRID today.

Thanks for fixing so quickly!
Brian
